[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "always"

[[services]]
name = "web"
source = "."
build.buildCommand = "composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache"
build.startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"

[[services]]
name = "queue-worker"
source = "."
build.buildCommand = "composer install --no-dev --optimize-autoloader"
build.startCommand = "php artisan queue:work database --queue=emails,default --sleep=3 --tries=3 --max-time=3600 --memory=512"